### ISSUE TITLE
Should all prepare_for_*() functions have defaults?

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/r2dii.plot#100]
As a user of `prepare_for_timeline()` I leaned that all except the first argument have defaults. For example, I can use it with 

``` r
library(r2dii.plot.static)

prepare_for_timeline(sda_target)
#> # A tibble: 50 x 4
#>     year line_name value extrapolated
#>    <dbl> <chr>     <dbl> <lgl>       
#>  1  2002 projected 0.228 FALSE       
#>  2  2003 projected 0.226 FALSE       
#>  3  2004 projected 0.224 FALSE       
#>  4  2005 projected 0.222 FALSE       
#>  5  2006 projected 0.220 FALSE       
#>  6  2007 projected 0.218 FALSE       
#>  7  2008 projected 0.216 FALSE       
#>  8  2009 projected 0.214 FALSE       
#>  9  2010 projected 0.212 FALSE       
#> 10  2011 projected 0.210 FALSE       
#> # … with 40 more rows
```

<sup>Created on 2021-04-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

Then I see other `prepare_for_*()` functions and I expect them to behave similarly. But this, for example, fails because all arguments of `prepare_for_techmix_chart()` are obligatory:

``` r
library(r2dii.plot.static)

prepare_for_techmix_chart(
  get_example_data()
)
#> Error in splice(dot_call(capture_dots, frame_env = frame_env, named = named, : argument "sector_filter" is missing, with no default
```

<sup>Created on 2021-04-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by MonikaFu** [comment]
In theory we could indeed set a default sector but I do find is a bit dangerous to return data for a sector that the user did not explicitly specify. Unless we maybe set it to `NULL` and then the user gets an empty data frame back? It won't be possible to plot using that data. though.

**Comment by maurolepore** [comment]
How about defaulting to all sectors — each in its own facet?

**Comment by MonikaFu** [comment]
The facet idea is nice but I need to explore whether it would work well. Since the plots we create here are quite complex, I am not sure how well the facets will behave.
