### ISSUE TITLE
Do we need to expose prepare_*() and process_*() functions?

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/r2dii.plot#101]
As I new user of the r2dii.plot.static I would like to have
a single interface to plot the data I get form upstream
packages like r2dii.analysis. Instead I find intermediate
steps involving `prepare_*()` and `process_*()` functions.

I think we briefly discussed this issue but I would like to
document here why the users may be interested in the
intermediate 'prepared' and 'processed' datasets, and see what
@AlexAxthelm thinks.

To me, right now those intermediate steps feel like
implementation details that could be hidden behind the
interface of the `plot_*()` functions. The ideal interface
would be something like this (in meta code)

    my_data %>%
      r2dii.match::do_something() %>%
      r2dii.analysis::do_something_else() %>%
      r2dii.plot.static::finally_plot_my_data()

**Comment by AlexAxthelm** [comment]
I like having the ability to inject additional commands for tweaking in the process:

```r
my_data %>%
  r2dii.match::do_something() %>%
  r2dii.analysis::do_something_else() %>%
  dplyr::filter(value > 50) %>%
  r2dii.plot.static::finally_plot_my_data()
```

but maybe we could have something like `quickplot_techmix(data)`, that runs the default processing step?

**Comment by maurolepore** [comment]
Nice idea of providing a quick plotting funcition. ggplot2 exports the generic [`autoplot()` ](https://ggplot2.tidyverse.org/reference/autoplot.html)that we could use with different classes of data. I've done it [here](https://forestgeo.github.io/fgeo.plot/reference/index.html). I'll explore this idea a bit further.

**Comment by AlexAxthelm** [comment]
I'd be very hesitant to implement `autoplot` for this use case. Mostly because then we would have to start implementing a real class system, where our different datasets each get their own classes. I'd rather keep the data as `tibble`s or `data.frame`s and differentiate the plot type based on function name. This also allows us to run multiple plot types against the same dataset (if applicable).

**Comment by maurolepore** [comment]
Noted. 

The class constructor could be a thin function that appends the new subclass to the "data.frame" (i.e. the output of `class(object)` would be `c("data.frame", "tbl", "our_class")`. But I acknowledge that the interface becomes a bit ackward

```r
autoplot(new_our_class(data))
```

The `quick_*()` is more straightforward.
