### ISSUE TITLE
How should users know how to construct the specs object?

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/r2dii.plot#116]
The specs argument takes a complex object and we seem to lack
a constructor or default -- whatever helps the user get
some output quickly, before learning the idyiosincrasies of
each plot_*() funciton.

If specs is compulsory, I see no benefit in passing it in a
dataframe instead of as loose arguments in the signature
of the funciton. Quite the opposite, it's rare that an
argument would take a dataframe other than the first 'data'
argument.

What alternatives could we brainstorm to make the interface
easier to use?

**Comment by MonikaFu** [comment]
I'd say that we should split it into separate vectors and make it clear that they are related. Maybe their names could start the same? Unless you have a better idea for how to do this?

**Comment by maurolepore** [comment]
If at all possible, I would make it an optional argument, guess something sensible, and let the user discover and adapt the guessed specs. Inspiration comes from the vroom package:

``` r
library(vroom)

path <- vroom_example("mtcars.csv")

# Guess spec
data <- vroom(path)
#> Rows: 32
#> Columns: 12
#> Delimiter: ","
#> chr [ 1]: model
#> dbl [11]: mpg, cyl, disp, hp, drat, wt, qsec, vs, am, gear, carb
#> 
#> Use `spec()` to retrieve the guessed column specification
#> Pass a specification to the `col_types` argument to quiet this message
# Show spec to the user in a way it's easy for them to adapt
spec(data)
#> cols(
#>   model = col_character(),
#>   mpg = col_double(),
#>   cyl = col_double(),
#>   disp = col_double(),
#>   hp = col_double(),
#>   drat = col_double(),
#>   wt = col_double(),
#>   qsec = col_double(),
#>   vs = col_double(),
#>   am = col_double(),
#>   gear = col_double(),
#>   carb = col_double(),
#>   .delim = ","
#> )

# Use custom spec
spec <- cols(
  model = col_character(),
  mpg = col_double(),
  cyl = col_double(),
  disp = col_double(),
  hp = col_double(),
  drat = col_double(),
  wt = col_double(),
  qsec = col_double(),
  vs = col_double(),
  am = col_double(),
  gear = col_double(),
  carb = col_double()
)

vroom(path, col_types = spec)
#> # A tibble: 32 x 12
#>    model         mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
#>    <chr>       <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
#>  1 Mazda RX4    21       6  160    110  3.9   2.62  16.5     0     1     4     4
#>  2 Mazda RX4 …  21       6  160    110  3.9   2.88  17.0     0     1     4     4
#>  3 Datsun 710   22.8     4  108     93  3.85  2.32  18.6     1     1     4     1
#>  4 Hornet 4 D…  21.4     6  258    110  3.08  3.22  19.4     1     0     3     1
#>  5 Hornet Spo…  18.7     8  360    175  3.15  3.44  17.0     0     0     3     2
#>  6 Valiant      18.1     6  225    105  2.76  3.46  20.2     1     0     3     1
#>  7 Duster 360   14.3     8  360    245  3.21  3.57  15.8     0     0     3     4
#>  8 Merc 240D    24.4     4  147.    62  3.69  3.19  20       1     0     4     2
#>  9 Merc 230     22.8     4  141.    95  3.92  3.15  22.9     1     0     4     2
#> 10 Merc 280     19.2     6  168.   123  3.92  3.44  18.3     1     0     4     4
#> # … with 22 more rows
```

<sup>Created on 2021-05-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by MonikaFu** [comment]
In many cases they can't be optional I believe. If we simplify the current setup to vectors, though, then maybe they will be easier for the user? They usually concern the order of variables and their labels and sometimes colours. Maybe something to think about on a higher level and come up with a solution that would work for all functions.
