### ISSUE TITLE
plot_trajectory() is insensitive to ggplot2 extensions

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/r2dii.plot#131]
I expected the output of `plot_trajectory()` to be extensible
with ggplot2 but `p` looks just like `p + labs(title = "blah")`, 
i.e. `labs(title = "blah")` achieves nothing. I suspect the
subclass "ggarrange" breaks the behaviour of the class "ggplot".

``` r
devtools::load_all(quiet = TRUE)

data <- prepare_for_trajectory_chart(
  process_input_data(example_data),
  sector_filter = "power",
  technology_filter = "renewablescap",
  region_filter = "global",
  scenario_source_filter = "demo_2020",
  value_name = "production"
)

scenario_specs <- dplyr::tibble(
  scenario = c("sds", "sps", "cps", "worse"),
  color = c("#9CAB7C", "#FFFFCC", "#FDE291", "#E07B73"),
  label = c("SDS", "STEPS", "CPS", "worse")
)

main_line_metric <- dplyr::tibble(metric = "projected", label = "Portfolio")

p <- plot_trajectory(data,
  scenario_specs_good_to_bad = scenario_specs,
  main_line_metric = main_line_metric
)

p
```

![](https://i.imgur.com/20UE66V.png)

FIXME: `labs("blah")` achieves nothing:

``` r
p + labs("blah")
```

![](https://i.imgur.com/phQkjTI.png)

The class “ggarrange” seems to break the behaviour of the “ggplot” object:

``` r
class(p)
#> [1] "gg"        "ggplot"    "ggarrange"
```

<sup>Created on 2021-05-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by MonikaFu** [comment]
This seems like another argument for finding a different way to replace the legend than using `ggarrange`
