### ISSUE TITLE
Move colour datasets to data/

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/r2dii.plot#144]
As we relentlessly simplify this package, I think keeping all
colour datasets in data/ is a good idea. For easy auto-completion
we may prefix them with `colour_*`, e.g.

`colour_technology`
`colour_palette`
`colour_sector`

NOTES:

1. Can we use snake_case everywhere? (`colour_technology` does not
   use snake_case).

2. Do all of these datasets need to be exported? Or some of them may
   be internal?

3. Can we rename the column `colour_hex` to `hex`? The content of that
   column is clear from the context: `r2dii.plot*::colour_palette$hex`

--

Relates to #108 #22

**Comment by MonikaFu** [comment]
I actually made a mistake in a previous issue related to this. It is actually issue #28 that is related. And it is also my preferred option to work on custom colour scales instead of dataset. Seems more convenient for the user. Therefore - not sure if the issue you start here is a priority.

**Comment by maurolepore** [comment]
I think #28 is a good idea, and different from this issue. #28 is about how the user applies colours but does not deal with where we store those colours or how we name the underlying datasets. 

If I understand correctly, we need to store the colours as a dataset somewhere, even if we use them only internally. Notice that CJ's idea uses the dataset `r2dii_palette_colours`:


```r
r2dii_pal <- function() {
  values <- r2dii_palette_colours()$colour_hex
  ...
}
```

If we pursue this issue and merge it, then this chunk would become this:

```r
r2dii_pal <- function() {
  values <- colour_palette$hex  # lives in either data/ (if exported) or R/sysdata.rda (if internal)
  ...
}
```

If the difference between this issue and #28 is clear and you still think this issue isn't worth doing, then feel  absolutely free to close this issue :+1:

**Comment by MonikaFu** [comment]
Now I see indeed that we might still need the colour datasets somewhere even if we create the custom colour scales. Let's keep this issue then. I do find it a good idea to treat them as a dataset rather than a function.
