### ISSUE TITLE
add more possible sectors to prepare_for_timeline()

### ISSUE THREAD

**Issue by cjyetman** [2DegreesInvesting/r2dii.plot#150]
> TODO separately.
> 
> > It doesn't address the missing "Coal" sector
> 
> > I think the investor data uses "Oil&Gas" not "oil and gas", so that probably won't work

_Originally posted by @maurolepore in https://github.com/2DegreesInvesting/r2dii.plot.static/issues/148#issuecomment-839188085_

following PR #148 and also mentioned in issue #145...

The `prepare_for_timeline()` function's argument `sector_filter` has a predefined list of possible values. The current list is...
https://github.com/2DegreesInvesting/r2dii.plot.static/blob/5107ea546191b64abbf21644b52cfd3e8249e6ba/R/prepare_for_timeline.R#L29-L37

The investor data often includes additionally "Coal" and "Oil&Gas", so it would be nice to add these to the list of possible sectors. Keep in mind that after PR #148 is merged, whatever value/s is/are passed to `sector_filter` is made all lower case before being matched against the default list of possible values.

**Comment by MonikaFu** [comment]
With the new interface the user does the filtering themselves so this is not an issue anymore.
