### ISSUE TITLE
In plot_timeine() the dashed lines have no reference in the label

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/r2dii.plot#157]
As in other ggplots, I expected the legend
to include a reference for both mappings: colour and 
linetype. Insted I see only a reference for colour. 
This makes the plot not fully interpretable by itself
and instead it needs additional text explaining the
meaning of the different linetypes. 

Is this intentional?

**Comment by MonikaFu** [comment]
Yes, I actually intentionally explain the dashed line in text and not in a legend to keep the story of the graph more coherent. I could consider adding the text inside of the chart to make sure that there is always some explanation of the dashed line provided.
