### ISSUE TITLE
`example_data` should be a package dataset, rather than a function

### ISSUE THREAD

**Issue by jdhoffa** [2DegreesInvesting/r2dii.plot#2]
`example_data` is the perfect candidate for a dataset, exported directly by the package (similar to `mtcars`).
Below is a checklist on how to do this. You will need to add a folder `data-raw`, and another folder will be generated while going through the checklist, `data`. 

You can skip the steps that involve testing the dataset, for now, as we can work on getting tests into the package another time :-)

### Checklist for developers to add `newdata` 
(with `data_dictionary` steps removed as agreed in #56 - not relevant for this project)

* [ ] Add "data-raw/newdata.csv" 
* [ ] In "data-raw/newdata.R", add something like: 
  ```
  # Source: @<contributor> <URL to issue or pull request>
  newdata <- readr::read_csv(here::here("data-raw", "newdata.csv"))
  use_data(newdata, overwrite = TRUE)
  ```
* [ ] `source("data-raw/newdata.R")`
* [ ] add the folder "data-raw/" to `.Rbuildignore`
* [ ] `usethis::use_r("newdata")`. Document `newdata` 
* [ ] `usethis::use_test("newdata")`. Add regression tests of `newdata`

**Comment by MonikaFu** [comment]
@maurolepore am I correct that one of the recent PRs solved this issue? Or is there a duplicate somewhere?
