### ISSUE TITLE
plot_trajectoryB() might gain 'main_line'

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/r2dii.plot#205]
Follows from https://github.com/2DegreesInvesting/r2dii.plot/pull/201#issuecomment-853135147

The excercise of developing `plot_trajectoryB()` exposed that the
most important information we need users to provide is the
'main_line', e.g. 'main_line = "projected"'. This is considerably
simpler than passing an ordered vector.

With this in mind, I wonder if prot_trajectoryB() should gain
the 'main_line' argument (how about calling it 'projected' instead?
or anything a bit more specific than 'main'?).

If I understand correctly, that would allow us to do the ordering inside
`plot_trajectoryB()` -- eliminating the risk that the user will forget
to order `metric`.

**Comment by MonikaFu** [comment]
Yes, indeed - that is correct. I kind of like to keep the name generic - (as main_line) - to keep the plotting functions rather independent of the names functioning in the data plotted. I don't think that what the user wants to plot will always be called projected. The point here is that the 'main_line' is the trajectory line that should have the most visual importance.
