### ISSUE TITLE
Should plot_techmixX() and friends error with more than one scenario?

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/r2dii.plot#212]
In `plot_techmixX()` and friends I think there is a bug
in the way we handle multiple scenarions. My guess is
that only one is used and other scenarios are ignored.

Is this a silent bug or a feature?

``` r
devtools::load_all()
#> ℹ Loading r2dii.plot

too_many_scenarios <- c("projected", "corporate_economy", "target_cps", "target_sds")
market_share %>%
  filter(
    scenario_source == "demo_2020",
    sector == "power",
    region == "global",
    metric %in% too_many_scenarios
  ) %>% 
  plot_techmixX()
```

![](https://i.imgur.com/OvZ7iNP.png)

<sup>Created on 2021-06-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by MonikaFu** [comment]
I'd say that it is a bug as in principle you might want to show more than one scenario (although I imagine it to rarely be the case).

**Comment by maurolepore** [comment]
Thanks! So what we expect is the plot to show as many scenarios as given (and not to throw an error asking to pick just one scenario). Right? If so I need to reword the title of this issue.
