### ISSUE TITLE
In plot_trajectory() is `normalize = FALSE` useful at all?

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/r2dii.plot#215]

**Comment by MonikaFu** [comment]
Did you mean to input an actual description of the issue but left the example description by accident? In any case - as far as I know it is useful sometimes to plot the actual values instead of the normalised ones (from what I understood from the analysts).

**Comment by maurolepore** [comment]
(Sorry I forgot to remove the issue-template. I removed it now.)

Okay, good to know the analysts find it useful. We discussed this before: Whether `normalize` and `extrapolate` should be an argument or a function. Before I leaned towards an argument inside the `plot_*()` functions, but now I'm starting to think they might make sense as arguments or loose functions in the r2dii.analysis package. Let's chat about it today, and maybe ask Jackson in the upcoming round of feedback.

**Comment by MonikaFu** [comment]
Yes - agree with you. Might make more sense for the 'analysis package'
