### ISSUE TITLE
Un-hide portfolio line in plot_trajectory()

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/r2dii.plot#223]
> LGTM except that the main line seems to be hidden behind a scenario line. I think the fix is to plot first the scenario lines, then the benchmark, finally the portflolio -- as ggplot is a layered framework, the most visible line will be the one plotted last.

https://github.com/2DegreesInvesting/r2dii.plot/pull/221#pullrequestreview-677657296

**Comment by maurolepore** [comment]
Is this solved @MonikaFu?﻿

**Comment by MonikaFu** [comment]
No, not yet.
