### ISSUE TITLE
In plot_trajectoryY() reuse Monika's ordering (form plot_trajectoryB())

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/r2dii.plot#233]
Last meeting we pruned the thick API (X) and decided to keep 
a version that exclude the recent ordering that @MonikaFu
implemented in plot_trajectoryB(). It would be nice to 
extract this feature in a general helper we could easily
use everywhere.

**Comment by MonikaFu** [comment]
This issue is not relevant anymore since we implemented 'main_line' argument.
