### ISSUE TITLE
Implement focused feedback

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/r2dii.plot#255]
This issue is to remind us to implement what we gathered 
via the google doc r2dii-plot_focused_feedback. This
includes multiple actionable steps, each of which may
become an issue in itself.

**Comment by MonikaFu** [comment]
I added a bunch of new issues. @maurolepore - if you feel like there is anything that still needs to be covered before the release - feel free to add it. Otherwise I think that this issue could be closed.
