### ISSUE TITLE
Remove the 'main_line' argument?

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/r2dii.plot#265]
If this first release focuses on banks data exclusively, then we
can safely assume the main line to plot will be "projected" and 
remove the `main_line` argument.

@MonikaFu is this correct? What do you think?

**Comment by MonikaFu** [comment]
If you are certain that this is always the name for the portfolio data then sure. Otherwise we could double check with @jdhoffa ??

**Comment by jdhoffa** [comment]
The output column `metric` of the `target_*` functions corresponding to the portfolio data is always `projected`, this is true!

**Comment by MonikaFu** [comment]
Awesome, thanks! Then yes - @maurolepore - we can remove the argument for now.
