### ISSUE TITLE
Remove the 'normalize' argument?

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/r2dii.plot#266]
> I think it could also make sense to house this in `r2dii.analysis`
-- @jdhoffa

The `normalize` argument has some change to become a feature in the
upstream package r2dii.analysis. Also, it's usefulness seems marginal,
i.e. something we might survive without in a first release. 

Shall we remove it from the first release while the discussion settles
on the long-term home for this feature?

**Comment by MonikaFu** [comment]
I would not remove it for now because the user will mostly plot normalized plots. It's almost never the case that the user wants to see the numbers that are not normalized. Therefore I would leave it as default behaviour until it is moved to analysis package.

**Comment by jdhoffa** [comment]
The usefulness is crucial, it's just the home that is uncertain.

**Comment by maurolepore** [comment]
My wording was confusing. The action seems crucial, but so much so that it seems we should just do it. 
In the interest of maximizing our options Monika and I plan to (1) keep the default behaviour, (2) remove the argument from the signature, (3) submit a PR to r2dii.analysis to normalize there (2DegreesInvesting/r2dii.analysis#312).
