### ISSUE TITLE
FIXME: plot_trajectory() with year 2019 errors ungracefully

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/r2dii.plot#275]
Via the entire r2dii workflow I arrived to a dataset that looks like the one below. Notice one row where year is 2019.
With this dataset `plot_trajectory()` throws an error which message is uninformative. We need to find out what's the
problem and help the user fix it (of fix it ourselves).

``` r
devtools::load_all()
#> ℹ Loading r2dii.plot

  data <- tibble::tribble(
  ~sector,     ~technology, ~year,  ~region, ~scenario_source,             ~metric,     ~production, ~technology_share,
  "power", "renewablescap", 2019L, "global",      "demo_2020", "corporate_economy",               1,               0.1,
  "power", "renewablescap", 2020L, "global",      "demo_2020", "corporate_economy",               1,               0.1,
  "power", "renewablescap", 2020L, "global",      "demo_2020",         "projected",               1,               0.1,
  "power", "renewablescap", 2020L, "global",      "demo_2020",        "target_sds",               1,               0.1,
)

plot_trajectory(data)
#> Error in if (delta_distance > max_delta_distance) {: argument is of length zero
```

<sup>Created on 2021-06-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by MonikaFu** [comment]
When trying to replicate the error with fake data I didn't get any error and the plot rendered correctly. 

``` r
devtools::load_all()
#> ℹ Loading r2dii.plot
library(tibble, quietly = TRUE)
library(dplyr, warn.conflicts = FALSE)

data <- market_share %>%
  filter(
    sector == "power",
    technology == "renewablescap",
    region == "global",
    scenario_source == "demo_2020",
    year <= 2025
  )

data <- data %>%
  filter(year == 2020) %>%
  mutate(year = 2019) %>%
  rbind(data)
plot <- plot_trajectory(data)
plot
```

![](https://i.imgur.com/BDq1KfF.png)

<sup>Created on 2021-06-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

Maybe you could provide the dataset that causes the error?

**Comment by maurolepore** [comment]
@jdhoffa r2dii.analysis output a dataset like the one in the
reprex. Is this a bug in r2dii.analysis? I mean, should we 
even get years earlier than 2020?

Sorry this is terse. I can explain more but now I just
wanted to ping you to not forget to report this potential
bug. ﻿

**Comment by jdhoffa** [comment]
In principle, the start year can be any year (2019, 2020, next year it will be 2021).
r2dii.analysis will output a dataset, for which the initial year is the earliest mutual year between the ALD and Scenario used, and all targets are calculated from this year. 

The "start year" will be whatever year the `projected` and `target_*` values are identical

Does any of this help?

**Comment by MonikaFu** [comment]
@jdhoffa - but in this case we get data for `corporate_economy` that starts before the scenarios and `projected`. Should this be the case? (I remember something similar for the example `sda` data).

**Comment by jdhoffa** [comment]
Oh shoot! You are indeed correct, this is unexpected behavior to me. 
While not "technically" a bug (since it's totally fine that the ALD should have production figures prior to the analysis), it is not what I would have thought was output. 

That said, I'm not sure if we should keep this in the output data or not. I can imagine it being useful for users to explore the corporate economy production values from prior years.

**Comment by jdhoffa** [comment]
I guess it's undesirable to have the `projected` and `target_*` values mutually dictate the start year of the plot? 

See in the reprex below how these "earlier" values only occur in the corporate economy (for both target functions). 

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(r2dii.data)
library(r2dii.match)
library(r2dii.analysis)

matched <- loanbook_demo %>% 
  match_name(ald_demo) %>% 
  prioritize()

out_market_share <- target_market_share(
  matched,
  ald_demo,
  scenario_demo_2020,
  region_isos_demo
)

out_market_share %>% 
  group_by(sector, technology, metric, region) %>% 
  summarize(min_year = min(year))
#> `summarise()` has grouped output by 'sector', 'technology', 'metric'. You can override using the `.groups` argument.
#> # A tibble: 223 x 5
#> # Groups:   sector, technology, metric [99]
#>    sector     technology   metric            region             min_year
#>    <chr>      <chr>        <chr>             <chr>                 <int>
#>  1 automotive electric     corporate_economy advanced economies     2002
#>  2 automotive electric     corporate_economy developing asia        2002
#>  3 automotive electric     corporate_economy europe                 2002
#>  4 automotive electric     corporate_economy global                 2002
#>  5 automotive electric     projected         global                 2020
#>  6 automotive electric     target_cps        global                 2020
#>  7 automotive electric     target_sds        global                 2020
#>  8 automotive electric     target_sps        global                 2020
#>  9 automotive electric_hdv corporate_economy developing asia        2002
#> 10 automotive electric_hdv corporate_economy global                 2002
#> # … with 213 more rows

out_sda <- target_sda(
  matched, 
  ald_demo, 
  co2_intensity_scenario_demo
)
#> Warning: Removing ald rows where `emission_factor` is NA

out_sda %>% 
  group_by(sector, emission_factor_metric) %>% 
  summarize(min_year = min(year))
#> `summarise()` has grouped output by 'sector'. You can override using the `.groups` argument.
#> # A tibble: 9 x 3
#> # Groups:   sector [2]
#>   sector emission_factor_metric min_year
#>   <chr>  <chr>                     <dbl>
#> 1 cement adjusted_scenario_demo     2020
#> 2 cement corporate_economy          2013
#> 3 cement projected                  2013
#> 4 cement target_demo                2013
#> 5 cement target_NA                  2013
#> 6 steel  adjusted_scenario_demo     2020
#> 7 steel  corporate_economy          2013
#> 8 steel  target_demo                2020
#> 9 steel  target_NA                  2020
```

<sup>Created on 2021-06-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by MonikaFu** [comment]
we were planning (and already doing it in some plots) to restrict the plot to start of `projected` and `target_*`. However I was thinking that maybe the plotting function is not actually the right place to do so... But I guess that if you say that it might be useful for the user to see this data then we're going to restrict it with a warning or something like that.

**Comment by jdhoffa** [comment]
Ya, I just can't think of a good reason to filter it out in the analysis stage right now, since we would just be filtering out perfectly good data. `projected` and `target_*` however obviously have to be defined for whatever scenario is input. 

I would say restrict it in the plot for now, but would be happily persuaded otherwise if people feel strongly!
