### ISSUE TITLE
In colour datasets make all values lowercase

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/r2dii.plot#285]
https://2degreesinvesting.github.io/r2dii.plot/reference/r2dii_colours

This should make it easier to add a single feature that modifies all 
legend labels consistently across plots. 

We could achieve this with `janitor::make_clean_names()`.

**Comment by MonikaFu** [comment]
I would agree to that if for `technology_colours` we add some helper that converts ugly to pretty labels.
