### ISSUE TITLE
Aline plot_emission_intensity() with updated r2dii.analysis

### ISSUE THREAD

**Issue by MonikaFu** [2DegreesInvesting/r2dii.plot#288]
Context: https://github.com/2DegreesInvesting/r2dii.analysis/issues/313

The names of `sda` dataset are going to change and the plotting code needs to be updated to reflect the change. In particular:
* example `sda` dataset should be updated.
* `plot_emission_intensity()` should be updated to use the right column name.
*  other parts of the code need checking

**Comment by maurolepore** [comment]
I asked @jdhoffa to keep the old names for now.

https://github.com/2DegreesInvesting/r2dii.analysis/pull/314#issuecomment-863538522
﻿
