### ISSUE TITLE
Did we agree to remove extrapolate?

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/r2dii.plot#294]
From a previous meeting I think to remember we decided to 
remove extrapolate, as it is not a standard PACTA feature
but a new idea tha Jackson proposed, and seems to be not
what George wants. 

I suggest we remove it from the initial release and maybe 
add it eventually if needed.

@MonikaFu do you agree?

**Comment by MonikaFu** [comment]
Agreed. That is what we agreed to do for now until the final decision on that feature is made.
