### ISSUE TITLE
Is qplot_fun() a good name for plot_fun()?

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/r2dii.plot#332]
The next release of r2dii.plot is planned to include a quick-plot 
functions that wraps the plot_*() functions and adds some convenient
features on top. What should be name such functions?

There is a `ggplot2::qplot()`. Should we name ours `r2dii.plot::qplot_*()`?

**Comment by MonikaFu** [comment]
I prefer fully spelled names so I'd be rather for `quick_plot_()`. However, sice `ggplot2` is a very popular package, if the name `qplot` is widely known and used (I didn't know it), I'd be willing to adopt it for our package.

**Comment by MonikaFu** [comment]
in the end we went for `qplot_*()`. See #359 #364
