### ISSUE TITLE
What if plot_ stays high-level and instead we export a lower level ggplot_*()

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/r2dii.plot#355]
Crazy idea:

It's a matter of names only but what plot_*() did what we discussed for
qplot_*() and we export a lower level ggplot_*() that outputs a super
minial object, e.g. with default ggplot themes, labels, etc. 

If most users will want the higher level funciton, then it makes
sense for it to have the most intuitive name (i.e. plot_ rather
than qplot_). 

I suspect that the few motivated users that want to build on a 
basic plot would find the current plot_*() still too magical, and
may prefer an even lower level set of functions like 

ggplot_techmix() + theme_2dii() + ...

**Comment by maurolepore** [comment]
In any case such low level functions would be useful for us 
internally, even if we don't export them. Right now each plot
kind of does its own thing. It would be nice to force ourselves
to extract the common elements and reuse them everywhere. This 
should make for a more consistent output and for code that
is easier to maintain.﻿

**Comment by MonikaFu** [comment]
closing this as we agreed on the naming in a verbal discussion. In the end we will go with `plot_*()` for the basic plots and `qplot_*()` for the quick plot to stick with the convention that was communicated to the stakeholders.
