### ISSUE TITLE
Missing test for trajectory

### ISSUE THREAD

**Issue by MonikaFu** [2DegreesInvesting/r2dii.plot#361]
When I added a helper.R to `tests\testthat` folder I added a function creating fake metrics and used it in trajectory testing (for too many scenarios and too many metrics) and also a check checking for number of metrics (so we don't try to add too many lines). It seems that this implementation is lost.

**Comment by maurolepore** [comment]
For the record, from conversations on slack this should help:

```bash
git log -S "bind_fake_market_share_metrics" --all -p
```

**Comment by MonikaFu** [comment]
closed in #359
