### ISSUE TITLE
`benchmark` should be plotted differently for low-carbon and high-carbon technologies

### ISSUE THREAD

**Issue by jdhoffa** [2DegreesInvesting/r2dii.plot#54]
We use two different methodologies to allocate scenario responsibility to high-carbon and low-carbon technologies. 
We compare the "high-carbon" technologies to the scenario by its "Technology Market Share", and we compare "low-carbon" technologies to the scenario by its "Sector Market Share", both of which are documented here: https://2degreesinvesting.github.io/r2dii.analysis/articles/target-market-share.html

I won't go into details as to why we do this, but I think this may have implications for how we plot the "benchmark". Since the scenario targets are "moving", and dependent on the portfolio, if we just plot the raw benchmark value, it is likely that the benchmark will align with a different scenario, depending on the portfolio, which is sort of peculiar and might not make sense.

If instead, we apply a similar approach to the benchmark as we do the scenario, and calculate the "moving benchmark" using either the sector market share, or technology market share, we can be sure that it will always be in the same position in relation to the other scenario targets, and we will have a more consistent output. 

I think this is a larger discussion/ potential methodological change and requires some brain space.

Thanks @georgeharris2deg for flagging this. 
@2diiKlaus @cjyetman and anyone else that would like to/ be able to give input would love to discuss. I have flagged this as well in Slack to help determine who else 

@MonikaFu this is a methodological question that needs a bit more thought. I leave it in this repository only because it currently seems to relate most to plotting, but it could very well live somewhere else. I mostly just wanted it to exist in an Issue so that it doesn't fall through the cracks.

**Comment by 2diiKlaus** [comment]
Can you @jdhoffa further explain what I meant by "Benchmark"? Isn't the scenario ending up to be the benchmark? Maybe this is connected to something that I am not aware of, but for me, it is difficult to comment on the issue.

**Comment by jdhoffa** [comment]
By benchmark, i"m referring to the "corporate economy" in the case of the banks, and the market indices in the case of EQ/CB

**Comment by MonikaFu** [comment]
@jdhoffa given [issue #269 in r2dii.analysis](https://github.com/2DegreesInvesting/r2dii.analysis/issues/269#issuecomment-865746277) can we close this one?

**Comment by jdhoffa** [comment]
Yes

**Comment by jdhoffa** [comment]
Yes
