### ISSUE TITLE
All obligatory arguments should come before those with defaults

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/r2dii.plot#96]
https://design.tidyverse.org/args-data-details.html

``` r
  devtools::load_all()
#> ℹ Loading r2dii.plot.static
```

Setup

``` r
data <- prepare_for_techmix_chart(
  process_input_data(get_example_data()),
  sector_filter = "power",
  years_filter = c(2020, 2025),
  region_filter = "global",
  scenario_source_filter = "demo_2020",
  scenario_filter = "sds",
  value_name = "technology_share"
)

power_colours <- get_r2dii_technology_colours("power")

bar_specs <- dplyr::tibble(
  metric_type = c(
    "portfolio_2020",
    "benchmark_2020",
    "portfolio_2025",
    "benchmark_2025",
    "scenario_2025"
  ),
  label = c(
    "Portfolio 2020",
    "Benchmark 2020",
    "Portfolio 2025",
    "Benchmark 2025",
    "Target SDS 2025"
  )
)
```

I can’t match by position

``` r
plot_techmix(
  data,
  power_colours,
  bar_specs
)
#> Error in filter(., .data$technology %in% unique(!!data$technology)): argument "df_tech_colours" is missing, with no default
```

I must match by name

``` r
# FIXME: plot_techmix() should return visibly so I don't need to call `print()`
print(
  plot_techmix(
    data,
    df_tech_colours = power_colours,
    df_bar_specs = bar_specs
  )
)
```

![](https://i.imgur.com/c3Sqgt8.png)

<sup>Created on 2021-04-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by maurolepore** [comment]
@AlexAxthelm, the enhancement I suggest here is influenced by the tidyverse design guide -- which we use in other r2dii packages. 

Should we use that guide here too?

**Comment by AlexAxthelm** [comment]
I agree that all required arguments should always come before optional ones (whether optional because it has a default, or because there is a guard that checks and ignores as part of the function body).

I also firmly believe that all function calls written in code should not use position matching, and we should use named arguments (even when using dplyr pipes), but that might be too strong a stance for a general style guide.
