### ISSUE TITLE
Should process_input_data(get_example_data()) become a dataset like sda_target?

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/r2dii.plot#98]
process_input_data(get_example_data()) outputs a dataset, and sda_target
too. Should both live in data/? Or maybe both live in inst/extdata?

If there is a reason for them to be different kinds of data, then let's
discuss it. Else it would be nice to be consistent.

**Comment by MonikaFu** [comment]
Yes, it should become a dataset. I think that we've also discussed it somewhere else already.
