### ISSUE TITLE
In prepare_for_timeline() explain what it means 'sda_target-type data'

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/r2dii.plot#99]
Do we need a link in ?prepare_for_timeline pointing to
wherever the user can produce sda_target-like data?
(I guess some function in the r2dii.analysis package?)

Or maybe we can point to an article in the pkgdown
website of r2dii.plot.static showing the process from
end to end -- including functions in the r2dii.analysis
package and maybe other packages upsteam?

**Comment by MonikaFu** [comment]
Yes, good idea.
